spring:
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    timeout: 1000
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0

